version: "3.5"

services:
      mysql:
        image: mysql:8.0.26
        container_name: databse-mysql
        restart: always 
        environment: 
        - MYSQL_ROOT_PASSWORD=123456
        ports:
        - 3306:3306
        